import { ReactComponent as PulseRateColor } from "../../../assets/img/PulseRateColor.svg";
import { ReactComponent as BloodPressureColor } from "../../../assets/img/BloodPressureColor.svg";
import { ReactComponent as WaterDrop } from "../../../assets/img/WaterDrop.svg";
import PulseRateGraph from "../../static/Graph/PulseRateGraph";
import VitalRangeGraph from "./VitalRangeGraph";
import RespiratonRateGraph from "../../static/Graph/RespirationRateGraph";
import { ReactComponent as Weight } from "../../../assets/img/Weight.svg";
import { ReactComponent as BmiIcon } from "../../../assets/img/BmiIcon.svg";
import { ReactComponent as BloodGlucose } from "../../../assets/img/BloodGlucose.svg";
import { ReactComponent as BloodOxygen } from "../../../assets/img/BloodOxygen.svg";
import { ReactComponent as BodyTemperature } from "../../../assets/img/BodyTemperature.svg";
import { ReactComponent as RespiratoryRate } from "../../../assets/img/RespiratoryRate.svg";

export const VitalsData = [
    {
        id: "bp",
        icon: <BloodPressureColor alt="Blood Pressure" />,
        title: "Blood Pressure",
        value: "124/82",
        unit: "mmHg",
        status: "Normal",
        date: "2023/10/23 at 4:27pm",
        detailedDate: "2023/10/23 4:25pm",
        standard: "120/80 mmHg",
        observation: "Normal",
        description: "Blood pressure is a vital sign that measures the health of your cardiovascular system.",
        rangeImage: "",
    },
    {
        id: "pr",
        icon: <PulseRateColor alt="Pulse Rate" />,
        title: "Pulse Rate",
        value: "76",
        unit: "Bpm",
        status: "Low",
        date: "2023/10/23 at 4:27pm",
        detailedDate: "2023/10/23 4:27pm",
        standard: "80 and 120 bpm",
        observation: "Low",
        description: "Pulse Rate refers to the number of times one’s heart beats per minute and, thus, indicates an individual's overall health.",
        // rangeImage: <VitalRangeGraph valueTop={124} valueBottom={82} unit="bpm" topMin={50} topMax={240} topStep={10} bottomMin={35} bottomMax={150} bottomStep={5} />,
        rangeImage: <PulseRateGraph />,
    },
    {
        id: "temp",
        icon: <BodyTemperature height="22px" width="23px" alt="Temperature" />,
        title: "Body Temperature",
        value: "98.6",
        unit: "°F",
        status: "Normal",
        date: "2023/10/22 at 11:00am",
        detailedDate: "2023/10/22 11:00am",
        standard: "97.8°F to 99.1°F",
        observation: "Normal",
        description: "Body temperature is a measure of the amount of heat present in the human body.",
        rangeImage: "/assets/temp-range.png",
    },
    {
        id: "spo2",
        icon: <BloodOxygen height="22px" width="23px" alt="SpO2" />,
        title: "Blood Oxygen",
        value: "98",
        unit: "%",
        status: "Normal",
        date: "2023/10/22 at 2:00pm",
        detailedDate: "2023/10/22 2:00pm",
        standard: "95% - 100%",
        observation: "Normal",
        description: "Blood oxygen, or oxygen saturation, is one of the most important vital signs that measure the amount of oxygen in a person's blood.",
        rangeImage: "/assets/spo2-range.png",
    },
    {
        id: "resp",
        icon: <RespiratoryRate height="22px" width="23px" alt="Respiratory Rate" />,
        title: "Respiratory Rate",
        value: "18",
        unit: "breaths/min",
        status: "Normal",
        date: "2023/10/21 at 3:30pm",
        detailedDate: "2023/10/21 3:30pm",
        standard: "12-20 breaths/min",
        observation: "Normal",
        description: "Respiratory rate is a vital sign used to measure the number of breaths taken per minute.",
        rangeImage: <RespiratonRateGraph />,
    },
    {
        id: "glucose",
        icon: <BloodGlucose height="22px" width="23px" alt="Blood Glucose" />,
        title: "Blood Glucose",
        value: "90",
        unit: "mg/dL",
        status: "Normal",
        date: "2023/10/21 at 9:00am",
        detailedDate: "2023/10/21 9:00am",
        standard: "70-99 mg/dL (fasting)",
        observation: "Normal",
        description: "Blood glucose, also known as blood sugar, is an important vital sign and a key indicator of overall health.",
        rangeImage: "/assets/glucose-range.png",
    },
    {
        id: "bmi",
        icon: <BmiIcon height="22px" width="23px" alt="BMI" />,
        title: "Body Mass Index",
        value: "21.5",
        unit: "kg/m²",
        status: "Normal",
        date: "2023/10/20 at 10:15am",
        detailedDate: "2023/10/20 10:15am",
        standard: "18.5–24.9",
        observation: "Normal",
        description: "The body mass index (BMI) is a measure that uses your height and weight to work out if your weight is healthy.",
        rangeImage: "/assets/bmi-range.png",
    },
    // {
    //     id: "cholesterol",
    //     icon: <WaterDrop alt="Cholesterol" />,
    //     title: "Cholesterol",
    //     value: "180",
    //     unit: "mg/dL",
    //     status: "Normal",
    //     date: "2023/10/19 at 8:45am",
    //     detailedDate: "2023/10/19 8:45am",
    //     standard: "<200 mg/dL",
    //     observation: "Normal",
    //     description: "Cholesterol is a type of fat found in your blood.",
    //     rangeImage: "/assets/cholesterol-range.png",
    // },
    {
        id: "weight",
        icon: <Weight alt="Weight" />,
        title: "Weight",
        value: "80",
        unit: "kg",
        status: "Normal",
        date: "2023/10/19 at 8:45am",
        detailedDate: "2023/10/19 8:45am",
        standard: "<200 mg/dL",
        observation: "Normal",
        description: "Body weight is a vital sign that reflects a person’s health and well-being.",
        rangeImage: "/assets/cholesterol-range.png",
    },
];
